static_root: http://static.menghuanwd.cn

origin_directory: /home/server/caishu/static/uploaders/origin
weixin_directory: /home/server/caishu/static/uploaders/weixin
avatar_directory: /home/server/caishu/static/uploaders/avatar
wap_directory: /home/server/caishu/static/uploaders/wap
web_directory: /home/server/caishu/static/uploaders/web
focus_directory: /home/server/caishu/static/uploaders/focus

origin_url: http://static.menghuanwd.cn/uploaders/origin
weixin_url: http://static.menghuanwd.cn/uploaders/weixin
avatar_url: http://static.menghuanwd.cn/uploaders/avatar
wap_url: http://static.menghuanwd.cn/uploaders/wap
web_url: http://static.menghuanwd.cn/uploaders/web
focus_url: http://static.menghuanwd.cn/uploaders/focus

web:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: menghuanwd_development
  pool: 5
  username: root
  password: caishuying
  host: 115.29.195.154
weixin_token: ximalaya23